<?php

/**
 * PluginStaticPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginStaticPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginStaticPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginStaticPage');
    }
}